name: Generate Documentation
on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  create-docs:
    runs-on: ubuntu-latest
    if: ${{ !contains(format('{0}', github.event.pull_request.title), '[Docs Update]') }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Install the tools
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          sudo apt install graphviz
          # sudo apt-get install pandoc
          sudo apt install texlive
          sudo apt install texlive-latex-extra
      - name: Run Doxygen
        run: |
          doxygen Doxyfile
      # - name: Convert to Markdown
      #   run: |
      #     [[ -d docs/markdown ]] || mkdir -p docs/markdown
      #       find docs/latex -type f -name "*.tex" -exec sh -c 'output_file="${1#docs/latex/}"; mkdir -p "docs/markdown/$(dirname "$output_file")"; pandoc -f latex -t markdown -o "docs/markdown/${output_file%.tex}.md" "$1"' _ {} \;
      # - name: Copy to svgs
      #   run: |
      #     [[ -d docs/svg ]] || mkdir -p docs/svg
      #     cp docs/html/*.svg docs/svg
      - name: Convert to pdf
        run: |
          [[ -d docs/pdf ]] || mkdir -p docs/pdf
          cd docs/latex
          pdflatex -output-directory=../pdf refman.tex
          cd ../..
          pwd
          cp docs/pdf/refman.pdf docs/G8R.pdf
      - name: Cleanup
        run: |
          [[ -d docs/latex ]] && rm -rf docs/latex
          [[ -d docs/pdf ]] && rm -rf docs/pdf
          # [[ -d docs/markdown ]] && rm -rf docs/markdown
          # [[ -d docs/html ]] && rm -rf docs/html
          # [[ -d docs/xml ]] && rm -rf docs/xml
      - name: Commit Doc Files
        if: github.event.pull_request.merged == true
        run: |
          git checkout -b docs-update-${{ github.run_id }}
          # git add docs/G8R.pdf
          git config --global user.name 'juanlittledevil'
          git config --global user.email 'juanlittledevil@users.noreply.github.com'
          # git commit -m "Automated documentation [Docs Update]"
          # git push origin docs-update-${{ github.run_id }}
          git fetch
      # - name: Checkout Source
      #   uses: actions/checkout@v4
      #   with:
      #     ref: docs-update-${{ github.run_id }}
      #     fetch-depth: 0
      - name: Create PR for the Docs
        if: github.event.pull_request.merged == true
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: docs/G8R.pdf
          commit-message: Automated documentation [Docs Update]
          title: Automated documentation [Docs Update]
          body: Automated documentation [Docs Update]
          branch: docs-update-${{ github.run_id }}
          base: main
          labels: documentation
          reviewers: juanlittledevil
          assignees: juanlittledevil