name: Generate Documentation
on:
  push:

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install the tools
        run: |
          sudo apt-get install doxygen
          sudo apt install graphviz
          sudo apt-get install pandoc
      - name: Run Doxygen
        run: |
          doxygen Doxyfile
      - name: Convert to Markdown
        run: |
          [[ -d docs/markdown ]] || mkdir -p docs/markdown
          find docs/html -type f -name "*.xhtml" -exec sh -c 'pandoc -f html -t markdown -o "docs/markdown/${1%.html}.md" "$1"' _ {} \;
      - name: Verify
        run: |
          ls -la docs/html
          ls -la docs/markdown
      # - name: Commit Doc Files
      #   run: |
      #     git add docs
      #     git config --global user.name 'juanlittledevil'
      #     git config --global user.email 'juanlittledevil@users.noreply.github.com'
      #     git commit -m "Automated documentation"
      #     git push