name: Generate Documentation
on:
  push:

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Doxygen
        run: |
          sudo apt-get install doxygen
          sudo apt install graphviz
      - name: Generate DoxigenFile
        run : |
          pwd
          ls -la
          doxygen -g Doxyfile
          echo "PROJECT_NAME = 'G8R'" >> Doxyfile
          echo "INPUT = src" >> Doxyfile
          echo "OUTPUT_DIRECTORY = docs" >> Doxyfile
          echo "GENERATE_LATEX = NO" >> Doxyfile
          echo "GENERATE_HTML = YES" >> Doxyfile
          echo "GENERATE_UML = YES" >> Doxyfile
          echo "GENERATE_CALL_GRAPH = YES" >> Doxyfile
          echo "CALL_GRAPH = YES" >> Doxyfile
          echo "CALLER_GRAPH = YES" >> Doxyfile
          ls -la
      - name: Doxyfile
        run: |
          cat Doxyfile
      - name: Generate Documentation
        run: | 
          doxygen Doxyfile
          ls -la