name: Generate PlantUML Diagrams
on:
  push:

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      # - name: Generate SVG Diagrams
      #   uses: holowinski/plantuml-github-action@main
      #   with:
      #     args: -v -tsvg diagrams/*.puml

      - name: Generate UML Diagrams
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          additional-packages: font-fira-code
