name: Generate Documentation
on:
  push:

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Doxygen
        run: |
          sudo apt-get install doxygen
          sudo apt install graphviz
      - name: Cat DoxigenFile
        run : |
          pwd
          ls -la
          cat Doxyfile
      - name: Run Doxygen
        run: |
          doxygen Doxyfile
      - name: Commit Doc Files
        run: |
          ls -ltra
      # - name: Commit DoxigenFile
      #   run: |
      #     git config --global user.name 'juanlittledevil'
      #     git config --global user.email 'juanlittledevil@users.noreply.github.com'
      #     git commit -am 'Automated Doxygen File'
      #     git push