name: Generate Documentation
on:
  push:

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Doxygen
        run: |
          sudo apt-get install doxygen
          sudo apt install graphviz
      - name: Generate DoxigenFile
        run : |
          pwd
          ls -la
          doxygen -g Doxyfile
          ls -la
      - name: Doxyfile
        run: |
          cat Doxyfile
      - name: Commit DoxigenFile
        run: |
          git add Doxyfile
          git config --global user.name 'juanlittledevil'
          git config --global user.email 'juanlittledevil@users.noreply.github.com'
          git commit -am 'Automated Doxygen File'
          git push