name: Generate Documentation
on:
  push:

jobs:
  create-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: L S
        run: |
          ls -la
          pwd
      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          working-directory: 'submodule/'
          doxyfile-path: 'docs/Doxygen'